#!/usr/bin/env bash
set -euo pipefail

WORKFLOW_DIR="${1:-${AGENT_WORKBENCH_IDEA_DIR:-${CODEX_WORKBENCH_IDEA_DIR:-$HOME/AgentWorkbench/Idea}}}"
SUMMARY_FILE="${2:-$WORKFLOW_DIR/handoff-summary.md}"

usage() {
  cat <<'EOF'
Usage:
  ./scripts/close_workflow.sh [workflow-dir] [summary-file]

Creates a handoff summary from a workflow folder generated by new_workflow.sh.
EOF
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

if [[ ! -d "$WORKFLOW_DIR" ]]; then
  echo "Workflow directory not found: $WORKFLOW_DIR"
  exit 1
fi

mkdir -p "$(dirname "$SUMMARY_FILE")"

relative_path() {
  local path="$1"
  python3 - "$WORKFLOW_DIR" "$path" <<'PY'
from pathlib import Path
import sys

root = Path(sys.argv[1]).resolve()
path = Path(sys.argv[2]).resolve()
print(path.relative_to(root))
PY
}

word_count() {
  local path="$1"
  wc -w <"$path" | tr -d ' '
}

line_count() {
  local path="$1"
  wc -l <"$path" | tr -d ' '
}

now="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
tmp_file="$(mktemp)"

{
  echo "# Workflow Handoff Summary"
  echo
  echo "- Workflow directory: \`$WORKFLOW_DIR\`"
  echo "- Generated at: \`$now\`"
  echo
  echo "## Files"
  echo

  found_markdown=0
  while IFS= read -r -d '' file; do
    rel="$(relative_path "$file")"
    words="$(word_count "$file")"
    lines="$(line_count "$file")"
    echo "- \`$rel\` - $lines lines, $words words"
    found_markdown=1
  done < <(find "$WORKFLOW_DIR" -type f -name '*.md' ! -name "$(basename "$SUMMARY_FILE")" -print0 | sort -z)

  if [[ "$found_markdown" == "0" ]]; then
    echo "- No markdown files found."
  fi

  echo
  echo "## Open Checkboxes"
  echo
  if ! grep -RIn --include='*.md' '^[[:space:]]*- \[ \]' "$WORKFLOW_DIR" 2>/dev/null | grep -v "$(basename "$SUMMARY_FILE")"; then
    echo "- No open checkboxes found."
  fi

  echo
  echo "## Empty Sections To Fill"
  echo
  python3 - "$WORKFLOW_DIR" "$(basename "$SUMMARY_FILE")" <<'PY'
from pathlib import Path
import sys

root = Path(sys.argv[1])
summary_name = sys.argv[2]
empty_sections: list[str] = []

for path in sorted(root.rglob("*.md")):
    if path.name == summary_name:
        continue
    lines = path.read_text(encoding="utf-8", errors="ignore").splitlines()
    for index, line in enumerate(lines):
        if not line.startswith("## "):
            continue
        following = []
        for next_line in lines[index + 1:]:
            if next_line.startswith("#"):
                break
            if next_line.strip():
                following.append(next_line.strip())
        if not following:
            empty_sections.append(f"- `{path.relative_to(root)}`: {line}")

if empty_sections:
    print("\n".join(empty_sections))
else:
    print("- No empty second-level sections found.")
PY

  echo
  echo "## Suggested Next Step"
  echo
  echo "Review the files above, fill empty sections, close open checkboxes, and copy the final memo into the relevant issue, pull request, or release notes."
} >"$tmp_file"

mv "$tmp_file" "$SUMMARY_FILE"
echo "created: $SUMMARY_FILE"
