#!/usr/bin/env bash
set -euo pipefail

WORKFLOW="${1:-}"
DEST_DIR="${2:-${AGENT_WORKBENCH_IDEA_DIR:-${CODEX_WORKBENCH_IDEA_DIR:-$HOME/AgentWorkbench/Idea}}}"

usage() {
  cat <<'EOF'
Usage:
  ./scripts/new_workflow.sh <workflow> [destination]
  ./scripts/new_workflow.sh --list
  ./scripts/new_workflow.sh --list --verbose

Workflows:
  issue-triage
  pr-review
  release-prep
  feature-discovery

Examples:
  ./scripts/new_workflow.sh issue-triage
  ./scripts/new_workflow.sh pr-review "$HOME/AgentWorkbench/Idea/my-review"
EOF
}

list_workflows() {
  if [[ "${1:-}" == "--verbose" ]]; then
    cat <<'EOF'
issue-triage - Reproducing, classifying, and planning an issue.
pr-review - Reviewing a pull request from multiple angles.
release-prep - Preparing a small release.
feature-discovery - Turning a feature idea into scope and tests.
EOF
    return
  fi
  cat <<'EOF'
issue-triage
pr-review
release-prep
feature-discovery
EOF
}

if [[ "$WORKFLOW" == "--list" ]]; then
  list_workflows "${2:-}"
  exit 0
fi

if [[ -z "$WORKFLOW" || "$WORKFLOW" == "-h" || "$WORKFLOW" == "--help" ]]; then
  usage
  exit 0
fi

case "$WORKFLOW" in
  issue-triage|pr-review|release-prep|feature-discovery)
    ;;
  *)
    echo "Unknown workflow: $WORKFLOW"
    usage
    exit 1
    ;;
esac

mkdir -p "$DEST_DIR"

write_if_missing() {
  local path="$1"
  if [[ -e "$path" ]]; then
    echo "skip existing: $path"
    return
  fi
  cat >"$path"
  echo "created: $path"
}

generate_role_prompts() {
  local roles_file="$DEST_DIR/pane-roles.md"
  local prompts_dir="$DEST_DIR/prompts"
  mkdir -p "$prompts_dir"

  python3 - "$roles_file" "$prompts_dir" "$WORKFLOW" <<'PY'
from pathlib import Path
import re
import sys

roles_file = Path(sys.argv[1])
prompts_dir = Path(sys.argv[2])
workflow = sys.argv[3]

text = roles_file.read_text(encoding="utf-8")
matches = re.findall(r"^Pane\s+(\d+):\s*(.+)$", text, flags=re.MULTILINE)

for pane_number, role in matches:
    prompt_path = prompts_dir / f"pane-{pane_number}.md"
    if prompt_path.exists():
        print(f"skip existing: {prompt_path}")
        continue
    prompt_path.write_text(
        f"""# Pane {pane_number} Prompt

You are Pane {pane_number} in a Local Agent Workbench session.

Workflow: {workflow}

Role: {role}

Use the shared workflow folder as your source of truth. Start by reading:

- `question.md`
- `pane-roles.md`

Then produce concrete notes for your role. Prefer writing a markdown file in the workflow folder instead of only answering in chat.

Keep the output practical for an open-source maintainer. Call out uncertainty clearly.
""",
        encoding="utf-8",
    )
    print(f"created: {prompt_path}")
PY
}

write_if_missing "$DEST_DIR/README.md" <<EOF
# $WORKFLOW

Generated by Local Agent Workbench.

Use this folder as the shared workspace for multiple Codex CLI panes.
Each pane should write to its assigned file instead of only answering in chat.
EOF

case "$WORKFLOW" in
  issue-triage)
    write_if_missing "$DEST_DIR/question.md" <<'EOF'
# Issue Triage

Paste the issue link, report, logs, and expected behavior here.
EOF
    write_if_missing "$DEST_DIR/pane-roles.md" <<'EOF'
# Pane Roles

Pane 1: Reproduce or restate the issue clearly.
Pane 2: Inspect likely code paths and related files.
Pane 3: Propose a minimal fix plan.
Pane 4: Identify regression tests and edge cases.
Pane 5: Check security, privacy, or data-loss risk.
Pane 6: Draft the maintainer response.
Pane 7: Look for related issues or duplicate patterns.
Pane 8: Challenge the leading diagnosis.
Pane 9: Synthesize the final triage memo.
EOF
    write_if_missing "$DEST_DIR/final-triage.md" <<'EOF'
# Final Triage

## Summary

## Reproduction

## Likely Cause

## Fix Plan

## Tests

## Maintainer Response
EOF
    ;;
  pr-review)
    write_if_missing "$DEST_DIR/question.md" <<'EOF'
# PR Review

Paste the pull request link, diff summary, test results, and review goals here.
EOF
    write_if_missing "$DEST_DIR/pane-roles.md" <<'EOF'
# Pane Roles

Pane 1: Behavior changes.
Pane 2: Test coverage.
Pane 3: Security and privacy risk.
Pane 4: Documentation impact.
Pane 5: Backward compatibility.
Pane 6: Performance or reliability.
Pane 7: Release-note impact.
Pane 8: Skeptical review.
Pane 9: Final review memo.
EOF
    write_if_missing "$DEST_DIR/final-review.md" <<'EOF'
# Final PR Review

## Verdict

## Blocking Issues

## Non-Blocking Suggestions

## Tests To Request

## Suggested Reply
EOF
    ;;
  release-prep)
    write_if_missing "$DEST_DIR/question.md" <<'EOF'
# Release Prep

Paste the target version, merged changes, known risks, and release constraints here.
EOF
    write_if_missing "$DEST_DIR/pane-roles.md" <<'EOF'
# Pane Roles

Pane 1: Changelog draft.
Pane 2: Breaking changes.
Pane 3: README and docs check.
Pane 4: Smoke test checklist.
Pane 5: Known issues.
Pane 6: Release notes.
Pane 7: Follow-up issues.
Pane 8: Risk review.
Pane 9: Final release checklist.
EOF
    write_if_missing "$DEST_DIR/release-checklist.md" <<'EOF'
# Release Checklist

- [ ] Tests pass
- [ ] Public safety audit passes
- [ ] README is current
- [ ] Changelog is current
- [ ] Known risks are documented
- [ ] Tag created
- [ ] Release notes published
EOF
    ;;
  feature-discovery)
    write_if_missing "$DEST_DIR/question.md" <<'EOF'
# Feature Discovery

Paste the user problem, constraints, examples, and open questions here.
EOF
    write_if_missing "$DEST_DIR/pane-roles.md" <<'EOF'
# Pane Roles

Pane 1: User workflow.
Pane 2: Existing code impact.
Pane 3: API or CLI design.
Pane 4: Tests and acceptance criteria.
Pane 5: Security and privacy.
Pane 6: Documentation.
Pane 7: Minimal implementation plan.
Pane 8: Alternative approach.
Pane 9: Final decision memo.
EOF
    write_if_missing "$DEST_DIR/decision-memo.md" <<'EOF'
# Feature Decision Memo

## User Problem

## Recommended Scope

## Non-Goals

## Implementation Plan

## Tests

## Risks
EOF
    ;;
esac

generate_role_prompts

echo
echo "Workflow ready:"
echo "  $DEST_DIR"
echo
echo "Launch panes with:"
echo "  AGENT_WORKBENCH_IDEA_DIR=\"$DEST_DIR\" ./scripts/launch_codex_tmux.sh"
echo
echo "Launch with role-specific prompts:"
echo "  AGENT_WORKBENCH_IDEA_DIR=\"$DEST_DIR\" AGENT_WORKBENCH_USE_ROLE_PROMPTS=1 ./scripts/launch_codex_tmux.sh"
